server:
  port: 8081

spring:
  datasource:
    username: username
    password: pass
    driver-class-name: org.postgresql.Driver

application:
  jwt:
    secretKey: 6bc9261a45c8b2abd388cf41972df0653a60c0a86826cd42ef86c4e582b9e838
    expirationSeconds: 600
    issuser: task.list.com
